//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserBehaviorCollection
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsPage
    {
        public int PageID { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> AccessTime { get; set; }
        public Nullable<System.DateTime> LastActiveTime { get; set; }
        public Nullable<int> HeaderID { get; set; }
        public string Actions { get; set; }
    }
}
