//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserBehaviorCollection
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsHeader
    {
        public int ID { get; set; }
        public string userkey { get; set; }
        public string browser { get; set; }
        public string os { get; set; }
        public string ip { get; set; }
        public string userdefine1 { get; set; }
        public string userdefine2 { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
